import { OfferCard } from "@/types/publisher";

export const PRESET_OFFER_CARDS: OfferCard[] = [
  {
    id: "preset-1",
    layout: "horizontal",
    backgroundStyle: "flat",
    discountLabel: "BEST VALUE",
    discountBadge: "+25% MORE",
    itemName: "Lifetime + 5200 Coins",
    itemAsset: "coins",
    price: "$44.99",
    source: "preset",
  },
  {
    id: "preset-2",
    layout: "horizontal",
    backgroundStyle: "flat",
    discountBadge: "+20% MORE",
    itemName: "Lifetime + 2000 Coins",
    itemAsset: "coins",
    price: "$18.49",
    source: "preset",
  },
  {
    id: "preset-3",
    layout: "horizontal",
    backgroundStyle: "flat",
    discountLabel: "MOST POPULAR",
    discountBadge: "+15% MORE",
    itemName: "950 Coins",
    itemAsset: "coins",
    price: "$9.49",
    selected: true,
    source: "preset",
  },
  {
    id: "preset-4",
    layout: "horizontal",
    backgroundStyle: "flat",
    discountBadge: "+10% MORE",
    itemName: "460 Coins",
    itemAsset: "coins",
    price: "$4.79",
    source: "preset",
  },
  {
    id: "preset-5",
    layout: "horizontal",
    backgroundStyle: "flat",
    itemName: "250 Coins",
    itemAsset: "coins",
    price: "$2.89",
    source: "preset",
  },
  {
    id: "preset-6",
    layout: "vertical",
    backgroundStyle: "gradient",
    discountLabel: "BEST VALUE",
    itemName: "Season Pass",
    itemAsset: "season-pass",
    price: "$9.99",
    source: "preset",
  },
  {
    id: "preset-7",
    layout: "horizontal",
    backgroundStyle: "textured",
    discountLabel: "MOST POPULAR",
    discountBadge: "+20% MORE",
    itemName: "1000 Gems",
    itemAsset: "gems",
    price: "$7.99",
    source: "preset",
  },
];
